<?php


	## Real mens code in debug level
	error_reporting(E_ALL);

	## Add functions
	require_once('files/php/functions.php');
	## Add regex
	require_once('files/php/regex.php');

	## No cache headers:
	header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
	header("Cache-Control: post-check=0, pre-check=0", false);
	header("Pragma: no-cache");

	## Quick MySQL connection
	#$dbpw = (gethostname() == 'sharky') ? "qaz123WSX" : null;
	$mysqli = new mysqli("localhost", "miglenco_sharky", "sharky2015", "miglenco_sharky");

	if (mysqli_connect_errno()) {
		printf("Connect failed: %s\n", mysqli_connect_error());
		exit();
	}

	## Let's get the current page
	$_pages = array("autocomplete","multicomplete","about","submit","bugreport","stats");
	$_page = isset($_GET['page']) && !empty($_GET['page']) ? strtolower($_GET['page']) : "multicomplete";
	$_page = in_array($_page,$_pages) ? $_page : "multicomplete";

	## Did the user want to download?
	if(isset($_GET['file'])){
		header('Content-type: application/octet-stream; charset=utf-8');
		header('Content-disposition: attachment; filename=sharky.txt');

			$query = "SELECT * FROM `questions` WHERE `valid`='1';";
			$row = $mysqli->query($query) or die($mysqli->error.__LINE__);
			echo "/*\r\n\r\n\tGenerated by Sharky.pimp\r\n\tSave the knowledge!\r\n\tQuestions: ".mysqli_num_rows($row)."\r\n\tDate: 2014-12-04 23:00\r\n\r\n*/\r\n\r\n";

			while($question = $row->fetch_assoc()){
				echo "Question [".$question['qid']."]: ".$question['title'] . "\r\n";
					for($j=1;$j<=7;$j++){
						if($question['a'.$j.'t']!="" &&  $question['a'.$j.'v']=="1") echo $question['a'.$j.'t']."". "\r\n";
					}
				echo "\r\n" . "\r\n";

			}



	exit;
	}

	if(isset($_GET['autocomplete'])){
	$js = "";
			$query = "SELECT * FROM `questions` WHERE `valid`='1';";
			$row = $mysqli->query($query) or die($mysqli->error.__LINE__);

			while($question = $row->fetch_assoc()){
					$this_question = qParser($question['title']);
					$this_question = str_replace("'","\\'",$this_question);
					$js .= "{ value: '".$this_question."', data: '";
					for($j=1;$j<=7;$j++){
					$this_question = trim(preg_replace( "/\r|\n/", "", preg_replace('/\s+/', ' ', str_replace(array("\r\n", "\r","\n\n","\n",PHP_EOL),null,$question['a'.$j.'t']))));
					$this_question = str_replace("'","\\'",$this_question);
						if($this_question!="" &&  $question['a'.$j.'v']=="1") $js .= $this_question."<br>";
					}
					$js .= "' }," . PHP_EOL;


			}

		$js = "
$(function(){

  var currencies = [
".$js."
  ];

  // setup autocomplete function pulling from currencies[] array
  $('#autocomplete').autocomplete({

	 lookup: currencies,

    onSelect: function (suggestion) {
      var thehtml = '<strong>Question:</strong> ' + suggestion.value + ' <br> <strong>Correct answers:</strong> ' + suggestion.data;
      $('#outputcontent').html(thehtml);
    }
  });



});";
	echo $js;
	exit;
	}




?>
<!DOCTYPE html>
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">

  <title><?=$_page;?> · Sharky the pimp</title>

  <link rel="stylesheet" type="text/css" href="files/index_files/styles.css">
<?php
# Fire statistics
if(file_exists('/var/apphome/firestats/php/db-hit.php')){
	require_once('/var/apphome/firestats/php/db-hit.php');
	fs_add_site_hit(1);
}
?>
</head>
<body>

  <header id="masthead" style="background-color:#00acee;">

    <div class="container">

      <!-- <ul class="network-nav nav">
        <li class="nav-search"><a href="submit.html" style="color:#fff;">Submit</a></li>
		<li class="nav-search"><a href="submit.html" style="color:#fff;">Download</a></li>
        <li class="nav-stats"><a href="stats.html" style="color:#fff;">Stats</a></li>
      </ul> -->

      <a href="/">
        <img class="logo" src="files/images/logo.png" alt="Sharky">
      </a>
		<h1  class="page-title" >Sharky The pimp</h1>
		<h3 class="tagline">Autocompleter for annoying performance assessments.</h3>

    </div>
  </header>

  <div id="content">

    <div class="container">

      <div class="sidebar">
        <ul class="site-nav nav">
		  <?php
		  foreach($_pages as $k)
			echo '<li class="nav-home"><a href="/'.$k.'.html">'.$k.'</a></li>';
		  ?>
      </div>

      <div class="main">
	  <?php
	  require_once("./files/php/".$_page.".php");
	  ?>
  </div>

    </div>

  <script type="text/javascript" src="files/js/jquery-1.9.1.min.js"></script>
  <script type="text/javascript" src="files/js/jquery.autocomplete.min.js"></script>
  <script type="text/javascript" src="?autocomplete=1<?php echo "&r=".urlencode(microtime());?>"></script>

  <!-- <script type="text/javascript" src="files/js/currency-autocomplete.js<?php echo "?r=".urlencode(microtime());   ?>"></script> -->

</body></html>

<?php

	$mysqli->close();
?>
